### ISSUE TITLE
Allow organisers do complete their profiles in order to edit events.

### ISSUE THREAD

**Issue by willian** [ricardovaleriano/call4paperz#70] opened 2014-11-18 13:08 UTC
I tried to edit my event but Call4Papers says that I need to complete my profile first, redirecting me to *Editing profile* page. I did that, but seems that it's not saving my email and, so, my profile is never completed and I can't edit my event.

Please, let me know if you need more informations.

**Comment by agaelebe** [comment] 2015-01-13 20:35
@ricardovaleriano I had the same problem here and could reproduce it in development although mailcatcher was not working for me.

I need to create a call4paperz for Guru-SP next meeting in February ASAP (preferably using guru-SP account).  :)

The email is not being updated because devise :confirmable is enabled, so the email needs to be confirmed but the email confirmation message is not being sent.

So we need to add this code to the update method of profiles_controller.rb:

      @user.send_confirmation_instructions if @user.unconfirmed_email.present?

Besides that, the token sent when a new account is registered via email is wrong. That is, new users that register by email cannot confirm their accounts. So besides that we need another change in the code.

Since devise 3.1, the code in the confirmation email view (views/mailer/confirmation_instructions.html.erb) changed.
So we need to change '@resource.confirmation_token' to just '@token':
 
    <p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @token) %></p>

Both changes, I think, should solve the issue.
If you want I can submit a pull request.

Or, If you want to address this even easier you could disable devise confirmable... But I think is not a good idea.

**Comment by agaelebe** [comment] 2015-01-13 20:42
@ricardovaleriano A, esquece sobre o mailcatcher.. só precisava de um refresh.. apareceram os emails aqui :dancer:

**Comment by ricardovaleriano** [comment] 2015-03-17 17:44
Apparently not an issue.
I'm closing this for now, ok? If the problem pops out again, then we can reopen it for a thoroughly investigation.

**Closed by ricardovaleriano** 2015-03-17 17:44 UTC
Labels: enhancement, urgent
